In [2]:
import seaborn as sns
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.isnull().sum()
df.shape

(891, 15)

In [4]:
df.dropna().shape

(182, 15)

In [5]:
#3column wise deletion
df.dropna(axis=1)

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,male,1,0,7.2500,Third,man,True,no,False
1,1,1,female,1,0,71.2833,First,woman,False,yes,False
2,1,3,female,0,0,7.9250,Third,woman,False,yes,True
3,1,1,female,1,0,53.1000,First,woman,False,yes,False
4,0,3,male,0,0,8.0500,Third,man,True,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,Second,man,True,no,True
887,1,1,female,0,0,30.0000,First,woman,False,yes,True
888,0,3,female,1,2,23.4500,Third,woman,False,no,False
889,1,1,male,0,0,30.0000,First,man,True,yes,True
890,0,3,male,0,0,7.7500,Third,man,True,no,True

In [6]:
df['age_mean']=df['age'].fillna(df['age'].mean)
df.info()
df.drop('age',axis=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
 15  age_mean     891 non-null    object
dtypes: bool(2), category(2), float64(2), int64(4), object(6)
memory usage: 87.6+ KB

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_mean
0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,22.0
1,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,38.0
2,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.0
3,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,35.0
4,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,27.0
887,1,1,female,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,19.0
888,0,3,female,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,<bound method Series.mean of 0 22.0\n1 ...
889,1,1,male,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,26.0
890,0,3,male,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,32.0

In [7]:
mode_val=df['embarked'].mode()
print(mode_val)

0    S
Name: embarked, dtype: object

In [8]:
import pandas as pd
import numpy as np
np.random.seed(123)

n_samples=1000
class_0_ratio=0.8
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
    
})
class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
    
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)
df

     feature_1  feature_2  target
0    -1.085631  -0.121167       0
1     0.997345  -2.008585       0
2     0.282978  -0.920647       0
3    -1.506295   0.168234       0
4    -0.578600  -1.319892       0
..         ...        ...     ...
995  -0.003155   0.845701       1
996  -0.430660  -1.119923       1
997  -0.146416  -0.359297       1
998   1.160176  -1.609695       1
999  -0.641512   0.013570       1

[1000 rows x 3 columns]

In [9]:
df_min=df[df['target']==1]
df_max=df[df['target']==0]

In [10]:
from sklearn.utils import resample

df_min_unsampled=resample(df_min,replace=True,n_samples=len(df_max),random_state=42)
df_min_unsampled

     feature_1  feature_2  target
902  -0.773806  -0.196443       1
979   1.482163   0.309863       1
892   0.231228   0.196570       1
814   0.024317  -0.067830       1
906   0.992992  -0.856650       1
..         ...        ...     ...
810  -0.530172   0.995595       1
884   0.021456  -0.287784       1
825  -0.558824   0.193094       1
862  -1.518326   0.111135       1
885   1.839348   1.011616       1

[800 rows x 3 columns]

In [11]:
##VERIFICATION OF CHANGES
df=pd.concat([df_max,df_min_unsampled])
df.value_counts('target')

target
0    800
1    800
Name: count, dtype: int64

## DOWNSAMPLING

-HIGHER VALUES KO NEECHE LANA

##UPSAMPLING
 
 -NEECHE WALI MINORITY KO MAJORITY K PAS LANA

In [12]:
##DOWNCASTING : 

import pandas as pd
import numpy as np
np.random.seed(123)

n_samples=1000
class_0_ratio=0.8
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
    
})
class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
    
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)
df

df_min=df[df['target']==1]
df_max=df[df['target']==0]

In [13]:
from sklearn.utils import resample

df_max_unsampled=resample(df_min,replace=False,n_samples=len(df_min),random_state=42)
df_max_unsampled
df=pd.concat([df_max_unsampled,df_min])
df
df.shape

(400, 3)