In [2]:
import pandas as pd
df=pd.DataFrame({'city':['NYC','london','paris','tokyo','NYC','paris'],
                 'price':[200,150,300,150,180,320]
                 })
df

     city  price
0     NYC    200
1  london    150
2   paris    300
3   tokyo    150
4     NYC    180
5   paris    320

In [8]:
mean_price=df.groupby('city')['price'].mean().to_dict()

mean_price

{'NYC': 190.0, 'london': 150.0, 'paris': 310.0, 'tokyo': 150.0}

In [9]:
df['city_encoded']=df['city'].map(mean_price)
df

     city  price  city_encoded
0     NYC    200         190.0
1  london    150         150.0
2   paris    300         310.0
3   tokyo    150         150.0
4     NYC    180         190.0
5   paris    320         310.0

## INTERNALS

In [10]:
import seaborn as sns
df=sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
mean_dict=df.groupby('time')['total_bill'].mean().to_dict()
mean_dict

/var/folders/cl/f_fmb9gx3tlb36p11rypnlyw0000gn/T/ipykernel_52458/1295617117.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_dict=df.groupby('time')['total_bill'].mean().to_dict()

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [23]:
df['enc_dinner']=df['time'].map(mean_dict)
df[['enc_dinner','time']]

    enc_dinner    time
0    20.797159  Dinner
1    20.797159  Dinner
2    20.797159  Dinner
3    20.797159  Dinner
4    20.797159  Dinner
..         ...     ...
239  20.797159  Dinner
240  20.797159  Dinner
241  20.797159  Dinner
242  20.797159  Dinner
243  20.797159  Dinner

[244 rows x 2 columns]