In [1]:
import pandas as pd

In [1]:
import pandas as pd 
df=pd.read_csv('social_media_engagement1.csv')
print(df)

    post_id   platform post_type         post_time  likes  comments  shares  \
0         1   Facebook     image   8/17/2023 14:45   2121       474     628
1         2   Facebook  carousel    5/14/2023 0:45   3660       432     694
2         3  Instagram      poll   2/21/2023 16:15   4955       408     688
3         4    Twitter     image   11/16/2023 0:45   1183        90     187
4         5    Twitter     video    5/23/2023 0:30   3499       247     286
..      ...        ...       ...               ...    ...       ...     ...
95       96  Instagram  carousel   7/12/2023 17:45     36       294     911
96       97    Twitter     video  10/27/2023 23:45    314       108     458
97       98    Twitter      text     8/5/2023 8:45    229       179      38
98       99  Instagram      poll  12/29/2023 12:15   5000       500     204
99      100  Instagram     image    6/6/2023 21:00   4483       357      25

     post_day sentiment_score
0    Thursday        positive
1      Sunday         neutral
2     Tuesday        negative
3    Thursday        negative
4     Tuesday        positive
..        ...             ...
95  Wednesday        positive
96     Friday         neutral
97   Saturday        positive
98     Friday        positive
99    Tuesday         neutral

[100 rows x 9 columns]

In [ ]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
data={ 'a':1,'b':2,'c':3 }
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [9]:
data=[10,20,30]
index=['a','b','c']
series=pd.Series(data,index=index)
print(series)

a    10
b    20
c    30
dtype: int64

In [56]:
#dataframes
#create a dataframe from a dict of list
data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,48],
    'City':['Banglore','New York','Chicago']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   30  New York
2   Jack   48   Chicago
<class 'pandas.core.frame.DataFrame'>

In [67]:
#dataframe from list of dict
data=[{'Name':"Krish","Age":25,"City":"Banglore"},
      {'Name':"john","Age":30,"City":"New York"},
      {'Name':"jack","Age":48,"City":"Florida"}]
df=pd.DataFrame(data)
print(df)

    Name  Age      City
0  Krish   25  Banglore
1   john   30  New York
2   jack   48   Florida

In [68]:

print(df)
df['Name']

    Name  Age      City
0  Krish   25  Banglore
1   john   30  New York
2   jack   48   Florida

0    Krish
1     john
2     jack
Name: Name, dtype: object

In [69]:
##accessing a specific element
print(df.at[2,'Name'])
print(df.iat[2,2])
df['Salary']=[50000,20000,1000000]

jack
Florida

In [70]:
df.drop("Salary",axis=1,inplace=True)

In [71]:
df

    Name  Age      City
0  Krish   25  Banglore
1   john   30  New York
2   jack   48   Florida

In [72]:
#add age to the column
df['Age']=df['Age']+1
df

    Name  Age      City
0  Krish   26  Banglore
1   john   31  New York
2   jack   49   Florida

In [73]:
df.drop(0,inplace=True)
df

   Name  Age      City
1  john   31  New York
2  jack   49   Florida

In [74]:
df.describe()

             Age
count   2.000000
mean   40.000000
std    12.727922
min    31.000000
25%    35.500000
50%    40.000000
75%    44.500000
max    49.000000