In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('Travel.csv')
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

# HANDLE MISSING VALUES
1. MISSING VALUES
2. CHECK DUPLICATES
3. CHECK DATATYPE
4. UNDERSTAND THE DATASET

In [3]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [4]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [5]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [6]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [7]:
df['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [8]:
df['Occupation'].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [9]:
df['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [10]:
df['Gender']=df['Gender'].replace('Fe Male','Female')

In [11]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [12]:
df['MaritalStatus']=df['MaritalStatus'].replace('Single','Unmarried')

In [13]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [14]:
null_features=[feat for feat in df.columns if df[feat].isnull().sum()>=1]
# check for ouliers if not much differnce in mean and 50 percentile then no outliers 
df[null_features].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [15]:
# fill age nulls with median age
df['Age'].fillna(df['Age'].median(),inplace=True)

# mode for the type the contract
df['TypeofContact'].fillna(df['TypeofContact'].mode()[0],inplace=True)
#mode() does NOT return a single value.
#It returns a Series, because there can be more than one mode.


#median duration of pitch
df['DurationOfPitch'].fillna(df['DurationOfPitch'].median(),inplace=True)

# mode no of followers
df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mode()[0],inplace=True)

#mode for preferred property star
df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0],inplace=True)

#median no of trips
df['NumberOfTrips'].fillna(df['NumberOfTrips'].median(),inplace=True)

#ode for the number of children visiting
df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0],inplace=True)

#median for monthly income
df['MonthlyIncome'].fillna(df['MonthlyIncome'].median(),inplace=True)

In [16]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [17]:
df.drop(['CustomerID'],axis=1,inplace=True)

# FEATURING ENGINEERING AND EXTRACTION

In [18]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [19]:
df['NumberOfPersonsVisiting']=df['NumberOfChildrenVisiting']+df['NumberOfPersonVisiting'].astype(int)
df.drop(columns=['NumberOfChildrenVisiting','NumberOfPersonVisiting'],inplace=True)

In [20]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,NumberOfPersonsVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [21]:
df

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,NumberOfPersonsVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,Manager,26576.0,4.0
4884,1,28.0,Company Invited,1,31.0,Salaried,Male,5.0,Basic,3.0,Unmarried,3.0,1,3,1,Executive,21212.0,6.0
4885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4.0,Standard,4.0,Married,7.0,0,1,1,Senior Manager,31820.0,7.0
4886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,4.0,Basic,3.0,Unmarried,3.0,0,5,0,Executive,20289.0,5.0
4887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4.0,Basic,4.0,Unmarried,3.0,1,3,1,Executive,24041.0,6.0

#  PERFORMING THE TRAIN TEST SPLIT AND OHE AND BE

In [22]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=['ProdTaken'],axis=1)
y=df['ProdTaken']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
# now performing one hot encoding and binary encoding
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe=OneHotEncoder(drop='first')
# we use drop first kyuki we have to drop 1 column , as n collumn hai to n-1 column me hi data hoga encoded
sc=StandardScaler()
cat_feat = x.select_dtypes(include='object').columns.tolist()

# WE CAN ALSO DO THIS BY -
#cat_feat=[feat for feat in df.columns if df[feat].dtype=='O']

num_feat = x.select_dtypes(exclude='object').columns.tolist()

#visne ek object bna dia ab vo ek bari me appl krega
preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",ohe,cat_feat),
        ("StandardScaler",sc,num_feat)
    ]
)

In [25]:
x_test

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,NumberOfPersonsVisiting
144,32.0,Company Invited,3,13.0,Small Business,Male,5.0,Deluxe,3.0,Married,1.0,0,2,0,Manager,19668.0,3.0
79,46.0,Self Enquiry,2,11.0,Small Business,Male,4.0,Deluxe,4.0,Married,1.0,1,5,0,Manager,20021.0,4.0
2098,37.0,Self Enquiry,3,22.0,Small Business,Male,4.0,Deluxe,3.0,Married,5.0,0,5,1,Manager,21334.0,3.0
4738,43.0,Self Enquiry,1,36.0,Small Business,Male,6.0,Deluxe,3.0,Unmarried,6.0,0,3,1,Manager,22950.0,5.0
2858,25.0,Self Enquiry,3,7.0,Large Business,Female,4.0,Basic,4.0,Unmarried,3.0,1,4,1,Executive,21880.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2908,38.0,Self Enquiry,1,7.0,Large Business,Female,4.0,Standard,3.0,Unmarried,6.0,0,5,1,Senior Manager,26169.0,5.0
2059,29.0,Self Enquiry,1,6.0,Salaried,Female,4.0,Basic,5.0,Married,2.0,1,1,0,Executive,17319.0,2.0
4872,35.0,Company Invited,1,24.0,Large Business,Male,5.0,Basic,3.0,Married,2.0,1,5,1,Executive,27178.0,5.0
843,26.0,Self Enquiry,1,13.0,Small Business,Male,1.0,Basic,3.0,Divorced,2.0,0,5,1,Executive,22347.0,3.0
2572,23.0,Self Enquiry,1,9.0,Large Business,Male,4.0,Basic,3.0,Divorced,2.0,0,5,1,Executive,21201.0,7.0

In [26]:
x_train=preprocessor.fit_transform(x_train)

In [27]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,-0.774151
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,0.643615
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,-0.065268
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,-0.065268
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,2.061382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.653841,1.284279,-0.725271,-0.674182,-0.632399,-1.506426,0.782966,-0.536973,0.643615
3906,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.455047,-0.898180,-0.718725,1.771041,-1.220627,-0.632399,1.408395,0.782966,1.529609,-0.065268
3907,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.455047,1.545210,0.282777,-0.725271,2.058043,-0.632399,-0.777720,0.782966,-0.360576,0.643615
3908,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,1.789549,1.284279,-0.725271,-0.127737,-0.632399,-1.506426,0.782966,-0.252799,0.643615
3909,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.776011,0.282777,-0.725271,-1.220627,1.581280,-0.049015,-1.277194,-1.082511,-1.483035

In [28]:
x_test=preprocessor.transform(x_test)

# to prevent dataleakage vrna fit_transform mer data will get to know ki test data bhi h

# RANDOM FOREST MACHINE LEARNING ALGO TRAINING

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,precision_score,r2_score,roc_auc_score
from sklearn.linear_model import RidgeCV

In [ ]:
models={
    "Decision Tree":DecisionTreeClassifier(),
    "Random Tree":RandomForestClassifier(),
    "Logistic Regression": LogisticRegression(),
    "NAIVE BAYES ": GaussianNB(),
    "SVC ": SVC(kernel="rbf"),
    "KNN" : KNeighborsClassifier(),
    "ADABoost":AdaBoostClassifier()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)
    #now do test data 
    y_pred_train=model.predict(x_train)
    y_pred=model.predict(x_test)
    print(list(models.keys())[i])
    print("----------------------------\n")
    #test performence for train data
    print("accuracy_score : ",accuracy_score(y_train,y_pred_train))
    print("confusion matrix : ",confusion_matrix(y_train,y_pred_train))
    print("classification report",classification_report(y_train,y_pred_train))

    print("----------------------------\n\n\n")

    print(list(models.keys())[i])
    print("----------------------------\n")
    #test performence for test data
    print("accuracy_score : ",accuracy_score(y_test,y_pred))
    print("confusion matrix : ",confusion_matrix(y_test,y_pred))
    print("classification report",classification_report(y_test,y_pred))
    print("----------------------------\n")

Decision Tree
----------------------------

accuracy_score :  1.0
confusion matrix :  [[3181    0]
 [   0  729]]
classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3181
           1       1.00      1.00      1.00       729

    accuracy                           1.00      3910
   macro avg       1.00      1.00      1.00      3910
weighted avg       1.00      1.00      1.00      3910

----------------------------



Decision Tree
----------------------------

accuracy_score :  0.9192229038854806
confusion matrix :  [[754  33]
 [ 46 145]]
classification report               precision    recall  f1-score   support

           0       0.94      0.96      0.95       787
           1       0.81      0.76      0.79       191

    accuracy                           0.92       978
   macro avg       0.88      0.86      0.87       978
weighted avg       0.92      0.92      0.92       978

----------------------------

Random Tree
----------------------------

accuracy_score :  1.0
confusion matrix :  [[3181    0]
 [   0  729]]
classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3181
           1       1.00      1.00      1.00       729

    accuracy                           1.00      3910
   macro avg       1.00      1.00      1.00      3910
weighted avg       1.00      1.00      1.00      3910

----------------------------



Random Tree
----------------------------

accuracy_score :  0.9335378323108384
confusion matrix :  [[784   3]
 [ 62 129]]
classification report               precision    recall  f1-score   support

           0       0.93      1.00      0.96       787
           1       0.98      0.68      0.80       191

    accuracy                           0.93       978
   macro avg       0.95      0.84      0.88       978
weighted avg       0.94      0.93      0.93       978

----------------------------

Logistic Regression
----------------------------

accuracy_score :  0.8460358056265984
confusion matrix :  [[3087   94]
 [ 508  221]]
classification report               precision    recall  f1-score   support

           0       0.86      0.97      0.91      3181
           1       0.70      0.30      0.42       729

    accuracy                           0.85      3910
   macro avg       0.78      0.64      0.67      3910
weighted avg       0.83      0.85      0.82      3910

----------------------------



Logistic Regression
----------------------------

accuracy_score :  0.83640081799591
confusion matrix :  [[762  25]
 [135  56]]
classification report               precision    recall  f1-score   support

           0       0.85      0.97      0.90       787
           1       0.69      0.29      0.41       191

    accuracy                           0.84       978
   macro avg       0.77      0.63      0.66       978
weighted avg       0.82      0.84      0.81       978

----------------------------

NAIVE BAYES
----------------------------

accuracy_score :  0.7066496163682865
confusion matrix :  [[2271  910]
 [ 237  492]]
classification report               precision    recall  f1-score   support

           0       0.91      0.71      0.80      3181
           1       0.35      0.67      0.46       729

    accuracy                           0.71      3910
   macro avg       0.63      0.69      0.63      3910
weighted avg       0.80      0.71      0.74      3910

----------------------------



NAIVE BAYES
----------------------------

accuracy_score :  0.6942740286298569
confusion matrix :  [[551 236]
 [ 63 128]]
classification report               precision    recall  f1-score   support

           0       0.90      0.70      0.79       787
           1       0.35      0.67      0.46       191

    accuracy                           0.69       978
   macro avg       0.62      0.69      0.62       978
weighted avg       0.79      0.69      0.72       978

----------------------------

SVC
----------------------------

accuracy_score :  0.9012787723785166
confusion matrix :  [[3147   34]
 [ 352  377]]
classification report               precision    recall  f1-score   support

           0       0.90      0.99      0.94      3181
           1       0.92      0.52      0.66       729

    accuracy                           0.90      3910
   macro avg       0.91      0.75      0.80      3910
weighted avg       0.90      0.90      0.89      3910

----------------------------



SVC
----------------------------

accuracy_score :  0.8650306748466258
confusion matrix :  [[774  13]
 [119  72]]
classification report               precision    recall  f1-score   support

           0       0.87      0.98      0.92       787
           1       0.85      0.38      0.52       191

    accuracy                           0.87       978
   macro avg       0.86      0.68      0.72       978
weighted avg       0.86      0.87      0.84       978

----------------------------

KNN
----------------------------

accuracy_score :  0.9470588235294117
confusion matrix :  [[3148   33]
 [ 174  555]]
classification report               precision    recall  f1-score   support

           0       0.95      0.99      0.97      3181
           1       0.94      0.76      0.84       729

    accuracy                           0.95      3910
   macro avg       0.95      0.88      0.91      3910
weighted avg       0.95      0.95      0.94      3910

----------------------------



KNN
----------------------------

accuracy_score :  0.8875255623721882
confusion matrix :  [[764  23]
 [ 87 104]]
classification report               precision    recall  f1-score   support

           0       0.90      0.97      0.93       787
           1       0.82      0.54      0.65       191

    accuracy                           0.89       978
   macro avg       0.86      0.76      0.79       978
weighted avg       0.88      0.89      0.88       978

----------------------------

ADABoost
----------------------------

accuracy_score :  0.8478260869565217
confusion matrix :  [[3129   52]
 [ 543  186]]
classification report               precision    recall  f1-score   support

           0       0.85      0.98      0.91      3181
           1       0.78      0.26      0.38       729

    accuracy                           0.85      3910
   macro avg       0.82      0.62      0.65      3910
weighted avg       0.84      0.85      0.81      3910

----------------------------



ADABoost
----------------------------

accuracy_score :  0.8353783231083844
confusion matrix :  [[772  15]
 [146  45]]
classification report               precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.75      0.24      0.36       191

    accuracy                           0.84       978
   macro avg       0.80      0.61      0.63       978
weighted avg       0.82      0.84      0.80       978

----------------------------

# PCA

In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Sample data
X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0]
])

# Step 1: Standardize data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 2: Apply PCA
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X_scaled)

print("Reduced Data:\n", X_pca)
print("Explained Variance:", pca.explained_variance_ratio_)