In [1]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
dataset=pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv')
dataset.head()

                                                                  Bejaia Region Dataset
day month year Temperature  RH  Ws Rain  FFMC DMC DC  ISI BUI FWI              Classes
01  06    2012 29          57  18  0     65.7 3.4 7.6 1.3 3.4 0.5            not fire
02  06    2012 29          61  13  1.3   64.4 4.1 7.6 1   3.9 0.4            not fire
03  06    2012 26          82  22  13.1  47.1 2.5 7.1 0.3 2.7 0.1            not fire
04  06    2012 25          89  13  2.5   28.6 1.3 6.9 0   1.7 0              not fire

## GET BASIC INFO AND ALL THE THINGS TO REMOVE

In [3]:
dataset[dataset.isnull().any(axis=1)]

                                                                                          Bejaia Region Dataset
Sidi-Bel Abbes Region Dataset NaN NaN  NaN NaN NaN NaN NaN  NaN  NaN    NaN  NaN  NaN                        NaN
14                            07  2012 37  37  18  0.2 88.9 12.9 14.6 9 12.5 10.4 fire                       NaN

# now we have to divide the dataset in 2 parts

In [7]:
dataset["Region"] = 0          # create column + default value
dataset.loc[122:, "Region"] = 1
df = dataset

/var/folders/cl/f_fmb9gx3tlb36p11rypnlyw0000gn/T/ipykernel_22022/3010655045.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  dataset.loc[122:, "Region"] = 1

TypeError: Slicing a positional slice with .loc is not allowed, Use .loc with labels or .iloc with positions instead.